version: "3.9"
services:
  sml.examplegrpc:
    environment:
      ConnectionStrings__DbContext: "Host=sml.examplegrpc.db; Port=5432; Database='${DB_DATABASE_NAME:-SML.ExampleGrpc}'; Username='${DB_USERNAME:-postgres}'; Password='${DB_PASSWORD:-postgresPWD}'"
      Install__Data: "./"
      Kestrel__EndPoints__Http__Url: "http://sml.examplegrpc:${SML_EXAMPLEGRPC_PORT:-8080}"
      Logging__LogLevel__Default : "Debug"
      RabbitMqSettings__HostName: "sml.examplegrpc.message.brocker"
      RabbitMqSettings__Port: "5672"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - ${SML_EXAMPLEGRPC_DOCKER_HOST_PORT:-8080}:${SML_EXAMPLEGRPC_PORT:-8080}

  sml.examplegrpc.db:
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgresPWD}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_DB: ${DB_DATABASE_NAME:-SML.ExampleGrpc}
    ports:
      - "${DB_CONTAINER_DOCKER_HOST_PORT:-55432}:5432"

  sml.examplegrpc.message.brocker:
    image: rabbitmq:3.8.10-management-alpine
    ports:
      - ${MESSAGE_BROCKER_PORT:-55672}:5672